import { mkdirSync } from "node:fs";

import type { Config } from "../config.js";
import { logger } from "../logger.js";
import { elevenLabsProvider } from "./elevenlabs.js";
import { googleTtsProvider } from "./google-tts.js";
import { geminiTtsProvider } from "./gemini-tts.js";
import { recordUsage } from "./usage.js";
import type { VoiceProvider, VoiceResult } from "./types.js";

// Order = spec priority: ElevenLabs → Google Cloud TTS → (Gemini TTS, our working fallback).
const PROVIDER_CHAIN: VoiceProvider[] = [elevenLabsProvider, googleTtsProvider, geminiTtsProvider];

/**
 * Generate narration for one episode. Tries each configured provider in order,
 * falling through on failure, and returns which one produced the audio.
 */
export async function generateVoice(
  cfg: Config,
  videoNumber: number,
  text: string,
): Promise<VoiceResult> {
  mkdirSync("audio", { recursive: true });
  const outPath = `audio/ep${videoNumber}.mp3`;

  const configured = PROVIDER_CHAIN.filter((p) => p.isConfigured(cfg));
  if (configured.length === 0) {
    throw new Error("No TTS provider is configured (set ELEVENLABS_API_KEY, GOOGLE_TTS_API_KEY, or GEMINI_API_KEY).");
  }

  let lastErr: unknown;
  for (const provider of configured) {
    try {
      logger.info(`Generating voice with ${provider.name}`, { videoNumber, chars: text.length });
      const { chars } = await provider.synthesize(cfg, text, outPath);
      recordUsage({ ts: new Date().toISOString(), videoNumber, provider: provider.name, chars });
      logger.info(`✅ Voice generated by ${provider.name}`, { videoNumber, chars, outPath });
      return { provider: provider.name, chars, outPath };
    } catch (err) {
      lastErr = err;
      logger.warn(`Provider ${provider.name} failed — trying next`, {
        error: err instanceof Error ? err.message : String(err),
      });
    }
  }
  throw new Error(`All TTS providers failed. Last error: ${lastErr instanceof Error ? lastErr.message : String(lastErr)}`);
}
